### ISSUE TITLE
IsoRetirement check constraints too strict

### ISSUE THREAD

**Issue by xrotwang** [glottolog/treedb#5]
The two constraints
https://github.com/glottolog/treedb/blob/eda76440b492c1879397ad7f1b6f54d5b81ab63b/treedb/models.py#L1143-L1144
might be too strict. See code `ajt` here https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3_Retirements.tab

**Comment by xflr6** [comment]
Fixed via https://github.com/glottolog/glottolog/pull/855
